### ISSUE TITLE
version.h not found

### ISSUE THREAD

**Issue by gianmarcoodorizzi** [ufocomp/apostol-ocpp#1]
Hello,

after issuing make inside cmake-build-release I get:

`make[1]: Entering directory '/home/user/Desktop/apostol-ocpp/cmake-build-release'
make[2]: Entering directory '/home/user/Desktop/apostol-ocpp/cmake-build-release'
make[2]: Leaving directory '/home/user/Desktop/apostol-ocpp/cmake-build-release'
make[2]: Entering directory '/home/user/Desktop/apostol-ocpp/cmake-build-release'
-- Found Git: /usr/bin/git (found version "2.27.0") 
-- Found Git
-- Current Git commit hash: 0590eaa
CMake Error at /home/user/Desktop/apostol-ocpp/AutoVersion.cmake:13 (file):
  file failed to open for reading (No such file or directory):

    /home/user/Desktop/apostol-ocpp/version.h

make[2]: *** [CMakeFiles/auto_increment_version.dir/build.make:57: CMakeFiles/auto_increment_version] Error 1
make[2]: Leaving directory '/home/user/Desktop/apostol-ocpp/cmake-build-release'
make[1]: *** [CMakeFiles/Makefile2:211: CMakeFiles/auto_increment_version.dir/all] Error 2
make[1]: Leaving directory '/home/user/Desktop/apostol-ocpp/cmake-build-release'
make: *** [Makefile:130: all] Error 2`

Since this file is being gitignored, how is it supposed to find it? Thank you

**Comment by apostoldevel** [comment]
Hello.

To build, run:
~~~
cd apostol-ocpp
./configure
~~~

**Comment by gianmarcoodorizzi** [comment]
Hello, thanks. I saw you have updated the README including the missing information. There are still other things that need updating in that readme.

Anyhow, is there any documentation for this project?

**Comment by apostoldevel** [comment]
> There are still other things that need updating in that readme.

To keep the project up to date, just run 
~~~
./configure
~~~
 or
~~~
 ./configure --update
~~~

> Anyhow, is there any documentation for this project?

Unfortunately no.

This project is closely related to a commercial project, and everything related to business logic (processing data from charging stations) is in a private area.
