### ISSUE TITLE
Chargers Do not appear On THe DashBoard

### ISSUE THREAD

**Issue by sait1801** [ufocomp/apostol-ocpp#10]
Hi, I tried to use docker run for this project.

I did not configure any ip, just localhost:9220 is in configs. As mentioned here

```
Edit file ocpp-cs/docker/www/config.js according to your requirements. Specify the correct addresses of your server.

Edit file ocpp-cs/docker/conf/sites/default.json add IP address your server:

For example, your server IP address is 192.168.1.100 or DNS name is ocpp-server.
```

I deployed the ocpp server on Google Kubernetes Engine, it works and I can see the logs. The chargers can connect. However I do not see any charger on the dashboard, only I can see and control them via cli logs.

What do you think is the problem here ? I do not have any dns hostname, but when I run the code locally, localhost:9220 shows the chargers. 

Thanks in advanced for your support 
<img width="860" alt="issue" src="https://github.com/apostoldevel/ocpp-cs/assets/44114999/eff1e98b-ee1d-4063-9dea-ed9790b35418">

**Comment by ufocomp** [comment]
Hi! Most likely, the problem is that you have created a CRM version of the application (with authorization and connection to PostgeSQL).

Replace `CMakeLists.txt` the file to the one in the `docker/CMakeLists.txt`. Configure and compile the `cs` again.

Good luck.

**Comment by sait1801** [comment]
Hi, thanks for the support. I tried that solution too, it didn't work. I pulled the apostoldlevel\cs image from dockerhub and deployed it. Still I cannot see the chargers, but I can control them on bash

**Comment by ufocomp** [comment]
Hi! If you took an image of the Central Server from Docker Hub then the result of launching the container should be as follows:
![image](https://github.com/apostoldevel/ocpp-cs/assets/26512301/703cec90-5b0a-4aeb-b35f-c0639dd49722)

If the result is different, then the problem is not related to the docker image and without a more detailed description of the problem, it will be difficult for me to help you in any way.

P.S. There were updates in the CS code today, and the image on the Docker hub was also updated (`docker pull apostoldevel/cs`).

**Comment by sait1801** [comment]
Okay, thanks for the return. It's probably the hostname problem, I will close here when I solved it

**Comment by sait1801** [comment]
Hi again, I pulled the latest image from dockerhub and pushed it to GKE again. It still does not show the stations but I can control the stations via swagger. 

However, I noticed something. When add my server ip to the hosts under conf/sites/default.json as following :
`"hosts": ["localhost:9220", "34.135.135.55:9220"]` the dashboard do not open. It stays in loading screen. I think I couldn't configure the host addresses correctly. I do not have any dns hostname, only external IP of my cluster. How should I configure 
`ocpp-cs/docker/www/config.js` and `ocpp-cs/docker/conf/sites/default.json` ?

Thanks for all the help 😊

**Comment by ufocomp** [comment]
Hi!

I can only give general recommendations:

Install the `mc` in your cs container:
~~~
docker exec -it cs apt install mc -y
~~~

Run mc:
~~~
docker exec -it cs mc
~~~

Go to the `cs` settings folder: `/etc/cs`
- Examine the event logs in `/etc/cs/logs`;
- Make sure that the `/etc/cs/cp` folder is present and that it is not empty;
- Check the parameters in `/etc/cs/cs.conf`;
~~~
[main]
...
master=true
...
[process/ChargePoint]
## default: false
enable=true
~~~

Write in the `/etc/cs/sites/default.json` your external IP address is 34.135.135.55:9220

~~~
{
  "hosts": ["localhost:9220", "34.135.135.55:9220"],
  "root": "/opt/cs/www"
}
~~~

Also specify the IP address in the file `/opt/cs/www/config.js`:
~~~
ocppApiDomain: "http://34.135.135.55:9220"
~~~

Exit in the mc and restart container:
~~~
docker restart cs
~~~

Enter [http://34.135.135.55:9220](http://34.135.135.55:9220) in the browser's address bar.

I hope that you will succeed.

**Comment by ufocomp** [comment]
In Firefox http://34.135.135.55:9220 opens. Problems in Chrome with CORS. It blocks access to http://localhost:9220 since the main site address is 34.135.135.55:9220. The recommendations above should solve this problem.

![image](https://github.com/apostoldevel/ocpp-cs/assets/26512301/bccb77dd-f3a1-4c22-a809-e7908ec567bf)

![image](https://github.com/apostoldevel/ocpp-cs/assets/26512301/ce960fb6-019b-4a52-a7f0-00133875cdf4)

**Comment by sait1801** [comment]
I have tried this and it worked!
Thank you guys for all the support. I really appreciate it.
![image](https://github.com/apostoldevel/ocpp-cs/assets/44114999/99de166f-d52c-47e0-bf30-9735e53056b7)

**Comment by sait1801** [comment]
I want to ask one more thing, How can I see the heartbeat and BootNotification messages from this Central System?

**Comment by ufocomp** [comment]
> I want to ask one more thing, How can I see the heartbeat and BootNotification messages from this Central System?

To do this, you will need a CRM system. You can use our cloud solution at: [https://cloud.ocpp-css.com](https://cloud.ocpp-css.com).

After registration, the URL for connecting the station will be indicated in the upper right corner. Set it in the settings of your charging station, and it will automatically appear in your personal account. Don't forget to add the station ID (Identity) to the link if the station settings require it. This solution is free for non-commercial use. 

If you plan to use CRM (OCPP CSS) for commercial purposes, then contact us via telegram https://t.me/apostoldevel to discuss the terms of purchase. After payment, we will deploy and configure the system on your server and domain, as well as integrate it with Google, FireBase, set up SMS notifications, mail and, most importantly, a payment system (whichever you choose). Integration and configuration are included in the price of the system.

**Comment by sait1801** [comment]
Hi again, thanks for the quick feedback. I wanted to signup to the cloud.ocpp-css.com but I couldn't. The websites says invalid token and I cannot validate my mail adress

**Comment by ufocomp** [comment]
> Hi again, thanks for the quick feedback. I wanted to signup to the cloud.ocpp-css.com but I couldn't. The websites says invalid token and I cannot validate my mail adress

Hi! Two emails have been sent to your email address.  The valid link is in the latter.

**Comment by sait1801** [comment]
Hi, thanks for the quick response. I got only one mail in my mailbox and when I try it, it says "Ticket not Found"

**Comment by ufocomp** [comment]
> Hi, thanks for the quick response. I got only one mail in my mailbox and when I try it, it says "Ticket not Found"

Hi! In any case, your account is already activated and you can log in.
