### ISSUE TITLE
ConnectorId is not an integer

### ISSUE THREAD

**Issue by sait1801** [ufocomp/apostol-ocpp#11]
Hi I just connected my real charger to the cs code and I control it via swagger try outs. I want to setChargeProfile but I cannot because schneider charger returns : connectorId is not integer even when I give 0 in curl. Can I set the connector Id via changeconfigureation or stg ? 

Thanks in advanced

**Comment by ufocomp** [comment]
Hi! Your request must be in JSON format. Make sure that the value of "Request body" in Swagger is `application/json`.

![image](https://github.com/apostoldevel/ocpp-cs/assets/26512301/d5cf19fd-a562-42de-9ffa-9bec9ab27db1)

**Comment by sait1801** [comment]
I tried that too but it returns a different error then : 
![image](https://github.com/apostoldevel/ocpp-cs/assets/44114999/975208f4-f4b3-4835-9772-d95d070ba097)

**Comment by ufocomp** [comment]
Yes, there was such a problem, fixed. Please update the build.

**Comment by ufocomp** [comment]
We have also updated the web shell. Now the data for the Charging Profile is transmitted correctly. 

![image](https://github.com/apostoldevel/ocpp-cs/assets/26512301/32723412-465f-4bb6-a810-e1a5bcecefbf)

Thanks you for contacting us and helping us find the bugs.

**Comment by sait1801** [comment]
Hi,thanks for the quick response. I tried swagger. The chargingscheduleperiod must be in array format as following: 
`{
  "connectorId": 0,
  "csChargingProfiles": {
    "chargingProfileId": 0,
    "transactionId": 0,
    "stackLevel": 0,
    "chargingProfilePurpose": "ChargePointMaxProfile",
    "chargingProfileKind": "Absolute",
    "recurrencyKind": "Daily",
    "validFrom": "2023-12-19T07:48:35.662Z",
    "validTo": "2023-12-19T07:48:35.662Z",
    "chargingSchedule": {
      "duration": 0,
      "startSchedule": "2023-12-19T07:48:35.662Z",
      "chargingRateUnit": "W",
      "chargingSchedulePeriod": [{
        "startPeriod": 0,
        "limit": 0,
        "numberPhases": 0
      }],
      "minChargingRate": 0
    }
  }
}`

This worked for me.
