### ISSUE TITLE
RemoteStopTransaction Returns Rejected

### ISSUE THREAD

**Issue by sait1801** [ufocomp/apostol-ocpp#12]
Hi again, 
I tried remote start and stop transaction via dashboard but I cannot stop charging because charger returns:
`{
  "status": "Rejected"
}`

What can be the reason for that ? 

Thanks in advance

![image](https://github.com/apostoldevel/ocpp-cs/assets/44114999/ba4260b7-847e-47f5-8fe7-a69a365b7da3)

**Comment by ufocomp** [comment]
Hi! Make sure that you have entered a valid transaction number. If the command is sent to the emulator, it does not save the transaction number after reconnecting (rebooting).

**Comment by sait1801** [comment]
I tried it on a real charger without any charging profile payload. I tried numbers from 0 to 300 for transaction id, still none of them were accepted. The error for real charger is :
`Transaction ID: 2, Response: {"error": {"code": 400, "message": "InternalError: No transaction with id '2' was found"}}`

**Comment by ufocomp** [comment]
To stop the charging session, you must first start it. Please read sections "4.8. Start Transaction" and "5.11. Remote Start Transaction" an OCPP protocol v 1.6.

**Comment by sait1801** [comment]
I used the RemoteStartTransaction for starting charging and it worked. (I left ChargingProfile part blank). Then, tried to remotestoptransaction again. It didn't work. How will I know the TransactionID, without giving the ChargeProfile here :
![image](https://github.com/apostoldevel/ocpp-cs/assets/44114999/5f6066e7-1ed9-4d31-846b-df8d510d4b6d)

Thanks, for the quick support 🙏

**Comment by ufocomp** [comment]
The charging profile has nothing to do with the number of the upcoming transaction. 

> 5.11. Remote Start Transaction
> 
> Central System can request a Charge Point to start a transaction by sending a RemoteStartTransaction.req. Upon
> receipt, the Charge Point SHALL reply with RemoteStartTransaction.conf and a status indicating whether it has
> accepted the request and will attempt to start a transaction.

> 4.8. Start Transaction
> 
> The Charge Point SHALL send a StartTransaction.req PDU to the Central System to inform about a transaction
> that has been started. If this transaction ends a reservation (see Reserve Now operation), then the
> StartTransaction.req MUST contain the reservationId.
> Upon receipt of a StartTransaction.req PDU, the Central System SHOULD respond with a StartTransaction.conf
> PDU. This response PDU MUST include a **transaction id** and an authorization status value.

In other words, after you have sent a RemoteStartTransaction command to the charging station, it will request permission from the Central System to start a charging session, and if the decision is positive, the Central System will return the transactionId.

**Comment by ufocomp** [comment]
A charging session cannot be started on a physical station without workload. A car or a special workload simulation device must be connected to the charging station. Without workload, the charging station immediately completes the transaction. You can request the status of the connectors from the charging station by sending a Trigger Message command with the StatusNotification parameter.

**Comment by sait1801** [comment]
Sorry for the missing information, I connected simulation device to the charger, the problem happened while simulating the charging session

**Comment by sait1801** [comment]
This reason is solved because the charger that I tried did no thave setchargeoprofilehandler.
