### ISSUE TITLE
Ocpp 2.0.1 Connection

### ISSUE THREAD

**Issue by sait1801** [ufocomp/apostol-ocpp#14]
Hi, this code is awesome and I just want to ask an question. I just connected an charger with ocpp 2.0.1 connection to this dashboard and it worked. Would that cause any problem ? 
`async with websockets.connect(
        "ws://<apostol ocpp 1.6 server>/ocpp/chargerdeneme",
        subprotocols=["ocpp2.0.1"],`

Thanks in advanced

**Comment by ufocomp** [comment]
Hello, thank you for your question. The implementation of OCPP 2.0.1 protocol support is scheduled for this summer. Keep an eye on the updates.
