### ISSUE TITLE
Monitoring SoC of the car

### ISSUE THREAD

**Issue by sait1801** [ufocomp/apostol-ocpp#15]
Hi again, I would like to ask a question about car's status check commands.
I wnat to get the current SoC of the car but metervalues command is not implemented here. What command should I use? 
The GetCompositeSchedule Does not return the SoC of the car.

Thanks in advanced

**Comment by ufocomp** [comment]
Hello! To trigger a MeterValues request You need to use the TriggerMessage command (more details in the protocol specification version 1.6 section 6.51. TriggerMessage.req).

![image](https://github.com/apostoldevel/ocpp-cs/assets/26512301/e17ba277-d456-4931-890f-daae99c46ffa)

Best regards,
OCPP CSS.

**Comment by sait1801** [comment]
Thanks for the support
