### ISSUE TITLE
Establishing ocpp communication

### ISSUE THREAD

**Issue by MariemNagga** [ufocomp/apostol-ocpp#2]
Hello,
How can I test communication between client and server using this library?
What should I do after running ocpp (sudo service ocpp start)?
Thank you.

**Comment by apostoldevel** [comment]
Hello! 

After running CSS, the web shell will be available at: [http://localhost:9220/dashboard](http://localhost:9220/dashboard).

Build is set to production by default (using PostgreSQL).

To build in emulator mode, change the following settings in the [CMakeLists.txt](https://github.com/apostoldevel/apostol-ocpp/blob/master/CMakeLists.txt) file:

```
WITH_AUTHORIZATION OFF
WITH_POSTGRESQL OFF
```

and run:
~~~
./configure
cd cmake-build-release
make
~~~

or see [Release](https://github.com/apostoldevel/apostol-ocpp/releases).

**Comment by MariemNagga** [comment]
Thank you so much, that was very helpful.

**Comment by MariemNagga** [comment]
After running this command `./daemon.sh` I received this error :
```
/home/mariem/Downloads/ocpp_1.0.5c5462e-b1_Linux/ocpp_1_0_5c5462e-b1/usr/sbin/ocpp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/mariem/Downloads/ocpp_1.0.5c5462e-b1_Linux/ocpp_1_0_5c5462e-b1/usr/sbin/ocpp)
/home/mariem/Downloads/ocpp_1.0.5c5462e-b1_Linux/ocpp_1_0_5c5462e-b1/usr/sbin/ocpp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/mariem/Downloads/ocpp_1.0.5c5462e-b1_Linux/ocpp_1_0_5c5462e-b1/usr/sbin/ocpp)
/home/mariem/Downloads/ocpp_1.0.5c5462e-b1_Linux/ocpp_1_0_5c5462e-b1/usr/sbin/ocpp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/mariem/Downloads/ocpp_1.0.5c5462e-b1_Linux/ocpp_1_0_5c5462e-b1/usr/sbin/ocpp)

```
is this error related to ubuntu version:
I'm using this version 
``` Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```
Thank you,

**Comment by apostoldevel** [comment]
The [release](https://github.com/apostoldevel/apostol-ocpp/releases) has been rebuilt, the problem should be fixed.

Thank you for contacting us.
