### ISSUE TITLE
Job for ocpp.service failed

### ISSUE THREAD

**Issue by MariemNagga** [ufocomp/apostol-ocpp#3]
Hello,

After testing the [release](https://github.com/apostoldevel/apostol-ocpp/releases/tag/untagged-3e6c66e85c971e73f649)
it worked but after trying to retest [ocpp framework](https://github.com/apostoldevel/apostol-ocpp) using this command "sudo service ocpp start", I got this error:
```
Job for ocpp.service failed because the control process exited with error code.
See "systemctl status ocpp.service" and "journalctl -xe" for details.
```
I have two questions  : 

1. What's the cause of this error, is it related to the release version?
2. What is the difference between running ocpp using release or using ocpp framework?

Thank you in advance.

**Comment by apostoldevel** [comment]
Hello!

The ocpp binary from this release is not installed as a system service.

You can do it yourself or in automatic mode, for this you need to [build ocpp from source codes](https://github.com/apostoldevel/apostol-ocpp#build-and-installation) on your computer.

For self-installation run:

1. Copy ocpp as root from `<release>/usr/sbin` to `/usr/sbin` folder;
2. Copy everything as root from `<release>/etc/ocpp` to the `/etc/ocpp` folder;
3. Change the settings in the file `/etc/ocpp/ocpp.conf`:
~~~
[daemon]
daemon=true
pid=/run/ocpp.pid
~~~
4. Download [unit.service](https://raw.githubusercontent.com/apostoldevel/apostol-ocpp/master/auto/unit.service);
5. [Create a systemd daemon](https://tuttlem.github.io/2018/02/03/create-a-systemd-daemon.html).

**Comment by apostoldevel** [comment]
> What is the difference between running ocpp using release or using ocpp framework?

The only difference is in the settings, both in the build and in the configuration file, is the source code the same.

Thank you for contacting us and good luck.
