### ISSUE TITLE
Unable to connect to  ws://ws.ocpp-css.com/

### ISSUE THREAD

**Issue by embeddedLance** [ufocomp/apostol-ocpp#5]
Hi  I am  trying to test  a  charge point  implemenation  with your server,  but the connection times out:

`    async with websockets.connect(
        # 'ws://188.93.211.35:9220/ocpp',
        "ws://ws.ocpp-css.com:9220/ocpp",
        # 'ws://csms.edrv.io:80/yszb/v9y0',
        subprotocols=['ocpp1.6'],
        timeout=10
    ) as ws:
    
    `
    The above  code succeeds  with other  servers.  Can  you  point out  the issue?  Or  the server does  not accept any external  charge  points.

**Comment by ufocomp** [comment]
Hello!

Thank you for your feedback.

We updated the system yesterday. This may have been the cause of your problem. Service work completed, try connecting again.

Valid public addresses to connect:
~~~
ws://ws.ocpp-css.com/ocpp/
ws://ocpp-css.com/ocpp/
~~~

Example 1: for a charge point with identity “CP001” connecting to a Central System with OCPP-J
endpoint URL "ws://ocpp-css.com/ocpp" this would give the following connection URL:
~~~
ws://ocpp-css.com/ocpp/CP001
~~~

If you have registered in the system, then you will have a private connection point:
~~~
ws://ocpp-css.com/ocpp/<account>
~~~

Example:
~~~
ws://ocpp-css.com/ocpp/9929329c44dfb18ad2a33df9c194dd85443b2fcd/
~~~

**Comment by embeddedLance** [comment]
Hello back!

Now the  server  is accessible  but  I  guess  the real  issue is that I  haven't  registered in  the system.  So I get
`websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200`

How can I register  in the system.  I have logged  into http://cs.ocpp-css.com/ocpp via google.

**Comment by ufocomp** [comment]
Registration is not required to connect the station to the system.

**But you didn't add stantion identity.**

~~~
203.135.42.* - - [16/Jun/2022:13:57:58 +0300] "GET /ocpp/ HTTP/1.1" 200 4033 "-" "Python/3.10 websockets/10.3"
~~~

Valid URL format:

~~~
ws://ocpp-css.com/ocpp/<identity>
~~~

OCPP-J 1.6 Specification
3.1.1. Connection URL
~~~
Example 1: for a charge point with identity “CP001” connecting to a Central System with OCPP-J
endpoint URL "ws://ocpp-css.com/ocpp" this would give the following connection URL:
Registration in the system is required if you want to manage the stations connected to the system: ws://ocpp-css.com/ocpp/CP001
~~~

You have successfully registered in the system.

Google authorization will direct you to the main service. To manage stations, go to http://cs.ocpp-css.com and log in with your login and password:

Your login and password matches your email address: `s*o@gmail.com` (change your password after logging into the main system https://ocpp-css.com).

**Comment by embeddedLance** [comment]
Finally I   have  a connection. This url worked:
`'ws://ws.ocpp-css.com/ocpp/918d6878c2062db718b1640bfd2be752684d0e89'`

**Comment by ufocomp** [comment]
In this case, the value `918d6878c2062db718b1640bfd2be752684d0e89` is taken as the station identifier.

Your previous connection request was also successful:
~~~
203.135.42.* - - [16/Jun/2022:15:41:07 +0300] "GET /ocpp/v9y0 HTTP/1.1" 101 228 "-" "Python/3.10 websockets/10.3"
~~~

Valid URL:
~~~
ws://ws.ocpp-css.com/ocpp/918d6878c2062db718b1640bfd2be752684d0e89/v9y0
~~~

Where:
`ws://ws.ocpp-css.com/ocpp` - Connection URL;
`918d6878c2062db718b1640bfd2be752684d0e89` - Account ID;
`v9y0` - Stantion identity.

**Comment by embeddedLance** [comment]
Hi, I just started working on this again. I am registered on ocpp-css.com and I am using the 

Link to connect stations :
ws://ocpp-css.com/ocpp/64baa8d0116d8e9a61ff5c3a89455fdee836b646

The websocket connection is successful but I can't see my station registered at the server :(
