### ISSUE TITLE
invalid RFID tag

### ISSUE THREAD

**Issue by embeddedLance** [ufocomp/apostol-ocpp#6]
I have been trying to test startTransaction(). I have tired to send the RFID Tag as a string of 8-20 characters But I always get the following response from the server:
Sent: [2,"1000061","StartTransaction",{"connectorId":1,"timestamp":"2022-09-06T12:59:28.000Z","idTag":"3705D5D7"}]
Received opcode=1
Received=[3,"1000071",{"transactionId": 0, "idTagInfo": {"expiryDate": "2022-09-07T12:02:46.981Z", "status": "Invalid"}}]

**Comment by ufocomp** [comment]
Hello!

Your RFID card `3705D5D7` has not been activated in the system. Two other cards (`5cd*1a17`, `42A3*L985`) were removed by you today.

**We have activated the `3705D5D7` card.**

Good luck.

**Comment by embeddedLance** [comment]
Thanks  a lot! How do you acativate the card? Can I activate it?

**Comment by ufocomp** [comment]
Simply click on the `state` icon and select the desired action from the context menu.
