### ISSUE TITLE
Unable to test my charger using the demo server

### ISSUE THREAD

**Issue by amtssp** [ufocomp/apostol-ocpp#8]
Thanks for your work, I really like your demo server and I'm hoping to test my Orbis Combi charger at your demo server
But I can't connect my charger.

I have added this in my charger OCPP setup:
ws://ws.ocpp-css.com/ocpp/my_charger_name     
BUT what port should I specify? I have tried with port 40 and 80 and 9220 but I cant connect?

Also after logging in at https://cs.ocpp-css.com/ocpp I'm unable to add a station. If I click on "Stations list" nothing happens.

I'm I doing something wrong?

**Comment by apostoldevel** [comment]
Hello! Your `EVVC4FA6B4B5C` charging station has successfully connected to the system, but you are unable to see it as it is not linked to your account.

To associate the charging station with your account, you need to specify the account (40 characters) in the connection link.

The connection link should look like this:
~~~
ws://ws.ocpp-css.com/ocpp/your_account/my_charger_name
~~~

Port: 80 for `ws://` scheme
Port: 443 for `wss://` scheme


Where "your_account" is your personal account in the system, which can be found in at https://css.ocpp-css.com.

Alternatively, you can provide me with your username in the system, and I will link the station manually.

**Comment by amtssp** [comment]
Thanks

I managed to connect - I thought I could use the user:demo password:demo to
test it?
But anyway I'm in, and have my charger connected via wss using the 40
character account id.

BUT I can't figure out how to "add a station" - What should I write in the
"network" field ? I have tried using wifi, ethernet, wss but that is not
correct.

Cheers

**Comment by apostoldevel** [comment]
Hello! 

The station is added automatically when connected, there is no need to add it manually.

The network means the electrical network (private, public). 

I have linked the Orbis charging station to your account, now it is available in your personal account.

**Comment by amtssp** [comment]
Thanks - I can see it now and is connected. Thank you very much

Where do I find the area where I can test my charger by sending different
commands to it? Like the first screenshot in github?

Cheers

**Comment by apostoldevel** [comment]
> _Where do I find the area where I can test my charger by sending different_

[https://cs.ocpp-css.com](https://cs.ocpp-css.com/)

Only there authorization by password. Therefore, install it in your personal account if you have registered under a Google account.

In addition: In the public network, the charging station will be available to all users (drivers) in the system. In a private network only for you.

**Comment by amtssp** [comment]
OK - I logged in at  https://cs.ocpp-css.com using the same name as in my
https://css.ocpp-css.com/crm/profile using my google account.

I changed the settings at my charger to using the same 40 character id that
I got from https://css.ocpp-css.com/crm/profile

So in the charger I have:
ws://ws.ocpp-css.com/ocpp/4ca18c3a872f13eaxxxxxxetc60/EVVxxxxxxxx4B5C
port 80
The charger indicates that it is connected using the above settings.

But there is no charger available in https://cs.ocpp-css.com  ?

**Comment by apostoldevel** [comment]
Judging by the logs, everything worked out for you ;-) If so, please close the issue.

**Comment by amtssp** [comment]
Yes it is partly working

So in short I can find my charger at
https://css.ocpp-css.com/crm

BUT
I can't figure out how to connect my charger so I can see it in
https://cs.ocpp-css.com/ocpp

I have tried using the link you provided in the first email in order to
establish a connection to https://cs.ocpp-css.com:

ws://ws.cpp-css.com/ocpp/4ca18c3a872f13eaxxxxxxetc60/EVVxxxxxxxx4B5C

port 80
It does not connect ?

.

**Comment by apostoldevel** [comment]
To make the station appear here https://cs.ocpp-css.com it must be physically connected. It is now disabled. Not so long ago, the station was in touch, and I saw it on the list. Please connect the station so I can understand why you don't have access to it.

ws//ws.cpp-css.com/ocpp/4ca18c3a872f13eaxxxxxetc60/EVVxxxxxxxx4B5C
This is the correct ws link ^

**Comment by amtssp** [comment]
I don't know what you did - but now I can see it .....
I'm using: 
ws://ws.ocpp-css.com/ocpp/4ca18c3a872f13ea2feb7xxxxeb6d1a60/EVVCxxxx4B5C

I will try to use your link - and report back

**Comment by apostoldevel** [comment]
![image](https://user-images.githubusercontent.com/91010417/234343887-365704a8-a611-4d85-b595-dab8d378d9f4.png)

I don't see any problems with access, everything works :)

**Comment by amtssp** [comment]
Yes it works - but not using this link:
ws//ws.cpp-css.com/ocpp/4ca18c3a872f13eaxxxxxetc60/EVVxxxxxxxx4B5C 

The charger indicate that it is not able to connect. Can you see it now ?

**Comment by apostoldevel** [comment]
![image](https://user-images.githubusercontent.com/91010417/234344978-fde9fc81-c2f7-4efc-9b96-41e036ce2439.png)

Not at the moment. The charging point is offline.

**Comment by amtssp** [comment]
Yep - so I need to use
 ws://**ws.ocpp-css.com**/ocpp/4ca18c3a872f13ea2feb7xxxxeb6d1a60/EVVCxxxx4B5C

I don't know why ws/**/ws.cpp-css.com**/ocpp/4ca18c3a872f13ea2feb7xxxxeb6d1a60/EVVCxxxx4B5C doesn't work.

Should I close this topic now?

**Comment by apostoldevel** [comment]
Oh! Domain name **cpp**-css.com - this is an **incorrect**, apparently the translator distorted it. 

Correct domain [ocpp-css.com](https://ocpp-css.com). 

I connected the emulator to your account as an apology:

![image](https://user-images.githubusercontent.com/91010417/234347724-d85b0a68-f240-430a-a19b-106b8eaf465a.png)

**Comment by amtssp** [comment]
Thanks - I'm  closing this topic in a moment.

The last question - is it possible to see the log, so I can see the JSON string the server sends to the charger?

**Comment by apostoldevel** [comment]
>  _is it possible to see the log, so I can see the JSON string the server sends to the charger?_

Yes, in OCPP Log. Or is he unavailable to you too?

![image](https://user-images.githubusercontent.com/91010417/234350778-b3a14afe-0641-40d1-973c-a8f76d7592d4.png)

**Comment by amtssp** [comment]
OK found it  - at the on the web page: https://css.ocpp-css.com/crm/station
Thank very much for your help

**Comment by ufocomp** [comment]
Hello!

You can also use our API:

[OCPP Log API](https://css.ocpp-css.com/docs/#/Log/post_ocpp_log_list)

![image](https://user-images.githubusercontent.com/26512301/234353254-54df24d9-358b-432d-8e0a-d2fbdf016355.png)

**Comment by amtssp** [comment]
Thanks - do I have access to use that?

**Comment by apostoldevel** [comment]
Yes, if you are familiar with Swagger. Click on the `Authorize` button and enter your `username` and `password` from the OCPP CSS personal account.
