### ISSUE TITLE
Can't connect my Charging Station to the server

### ISSUE THREAD

**Issue by sait1801** [ufocomp/apostol-ocpp#9]
Hi,

I'm currently in the process of integrating my charger with the central system, and I've encountered an issue. I attempted to connect my charger to ws://ws.my-ocpp-server.com, but unfortunately, it didn't work as expected. I would appreciate some clarification and guidance on the proper method to successfully add my charger to the central system.

**Comment by ufocomp** [comment]
Hi! We need more data. 

First, try connecting to our server. Connection URL: [ws://cloud.ocpp-css.com/ocpp](ws://cloud.ocpp-css.com/ocpp)

**Example**: If the identity of the charging station `CP-0001`, then the connection string will be as follows: [ws://cloud.ocpp-css.com/ocpp/CP-0001](ws://cloud.ocpp-css.com/ocpp/CP-0001).

You can view and test the charging station using the [OCPP web application](https://cs.ocpp-css.com/ocpp):

~~~
username: demo
password: demo
~~~

**Comment by sait1801** [comment]
Hi, thanks for fast return,
I am trying to connect this python charge point implementation code to this ocpp-cs software but getting error.
The charge_point code is : https://github.com/mobilityhouse/ocpp/blob/master/examples/v16/charge_point.py
The error is about SSL error, I tried you cloud but got same error there too

**Comment by sait1801** [comment]
I will try to implement the ocpp-cs in cloud native environment and get back to you ASAP
